FROM resin/%%RESIN_MACHINE_NAME%%-debian

RUN apt-get update \
	&& apt-get install ghc cabal-install \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY simple-server-haskell.cabal .

RUN cabal update && cabal install --only-dependencies

COPY src/ ./src

RUN cabal build

ENV INITSYSTEM on

COPY start.sh .

RUN chmod +x start.sh

CMD "./start.sh"
